### PR TITLE
Fix some small things

### LINKED ISSUE #1: Restrict backend proxy to toggl and tick

### LINKED ISSUE #3: Automatically select last month
on feb 12 select jan1-jan31
lets say after the middle of the month, on feb 26 select feb1-feb28

### LINKED ISSUE #6: Ensure errors and workarounds
Ensure that errors are propagated to the ui, and allow to renew the session if it gets outdated (as an error prevention mechanism)

### LINKED ISSUE #9: Before 10th show previous month

### PR DESCRIPTION
**Pull request by davidkarolyi**
This PR consists of some small fixes:
- Fix faulty date range values, and set the default range to the current month.
- Sanitize requests handled by the proxy API.
- Add a little bit more detailed error message when a request fails.

### CODE REVIEW

File: lib/store/store.ts [hunk 1]
```diff
@@ -0,0 +1,340 @@
...
+  }
+
+  async getSourceTimeEntries() {
+    const { error } = await this.asyncAction(
+      this.sourceTimeEntries,
+      async () => {
+        const entries = await this.source.value?.getTimeEntries(
+          this.correctedDateRange[0] as Date,
+          this.correctedDateRange[1] as Date
+        );
```
Comment (sorgloomer) [inline lib/store/store.ts:219]: This makes toggl entries from the last day of the month disappear for me.
While Tick expects and filters by plain date values, Toggl filters the entries being in the datetime interval provided. That means we instead of filtering until `2022-01-31 00:00:00` we have to filter until `2022-01-31 23:59:59`. Let's round it up and just add a day to the end date. Inside the TogglAdapter, not here.

Here, just pass `this.dateRange[0], this.dateRange[1]`

**Review by sorgloomer — CHANGES_REQUESTED** [review]
Nice! I have concerns about that `correctedDateRange` thing, I tried to condensate my thoughts but let's talk about it next time

File: lib/store/store.ts [hunk 2]
```diff
@@ -0,0 +1,340 @@
...
+
+  async getTargetTimeEntries() {
+    if (!this.selectedTargetTask) this.setTargetTaskNotSelectedError();
+    else {
+      const { error } = await this.asyncAction(
+        this.targetTimeEntries,
+        async () => {
+          const entries = await this.target.value?.getTimeEntries(
+            this.correctedDateRange[0] as Date,
+            this.correctedDateRange[1] as Date
```
[the remark this answers is not in the document]
Comment (davidkarolyi) [reply lib/store/store.ts]: Nice! It looks like I had some misunderstanding on how the toISOString function worked, and that caused the incorrect response from Tick. I used your second suggestion and moved all date correction logic to the respective adapters.

File: lib/store/store.ts [hunk 3]
```diff
@@ -0,0 +1,340 @@
...
+  }
+
+  private get correctedDateRange(): DateRange<Date> {
+    const [startDate, endDate] = this.dateRange;
+    const correctedStartDate = startDate
+      ? subMinutes(startDate, startDate.getTimezoneOffset())
+      : null;
+    const correctedEndDate = endDate ? endOfDay(endDate) : null;
+    return [correctedStartDate, correctedEndDate];
+  }
```
[the remark this answers is not in the document]
Comment (davidkarolyi) [reply lib/store/store.ts]: Good point, that was sloppiness on my part. Fixed, thanks!

File: lib/store/store.ts (hunk 1 above)
Comment (davidkarolyi) [reply lib/store/store.ts]: I ended up using the `startOfDay` and `endOfDay` functions from `date-fns` in the Toggl adapter. This will be resolved in dates like this: `2022-01-30 23:00:00` - `2022-01-31 22:59:59`. So it has the timezone offset, but Toggl handles these dates precisely, so we should get back every entry we wanted.

**Comment by davidkarolyi** [comment]
I also fixed the default date range (#9) in this PR, so it will show the previous month before 10th of the actual month.

File: lib/adapters/tick.ts [hunk 4]
```diff
@@ -84,8 +85,8 @@ export class TickAdapter implements TargetAdapter<TickCredentials> {
       url: `${this.subURL}/entries.json`,
       headers: this.authHeaders,
       params: {
-        start_date: from.toISOString().split("T")[0],
-        end_date: to.toISOString().split("T")[0],
+        start_date: localizedPlainDateToUTC(from).toISOString().split("T")[0],
+        end_date: localizedPlainDateToUTC(to).toISOString().split("T")[0],
```
Comment (sorgloomer) [inline lib/adapters/tick.ts:89]: please extract this into a new function that could be used like:
 ```suggestion
        start_date: localPlainDateToString(from),
        end_date: localPlainDateToString(to),
```

File: lib/store/store.ts [hunk 5]
```diff
@@ -56,7 +62,7 @@ export class Store<S extends AdapterCredentials, T extends AdapterCredentials> {
     this.alert = alert;
   }
 
-  setDateRange(dateRange: DateRange<Date>) {
+  setDateRange(dateRange: [Date, Date]) {
```
Comment (sorgloomer) [inline lib/store/store.ts:65]: Name it, `type DateRange = [Date, Date]`

**Review by sorgloomer — APPROVED** [review]

File: lib/store/store.ts [hunk 6]
```diff
@@ -8,13 +8,19 @@ import {
...
 export class Store<S extends AdapterCredentials, T extends AdapterCredentials> {
   alert: Alert | null = null;
-  dateRange: DateRange<Date> = [subWeeks(startOfToday(), 2), startOfToday()];
+  dateRange: [Date, Date] =
+    new Date().getDate() <= 10
+      ? [
+          startOfMonth(subMonths(new Date(), 1)),
+          endOfMonth(subMonths(new Date(), 1)),
+        ]
+      : [startOfMonth(new Date()), endOfMonth(new Date())];
```
Comment (sorgloomer) [inline lib/store/store.ts:23]: Please extract it into a function, and make sure to call `new Date()` only once in that function
